# Generated by Django 2.2 on 2020-10-16 04:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=ckeditor.fields.RichTextField(default='Text'),
            preserve_default=False,
        ),
    ]
