# Generated by Django 2.2 on 2020-10-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill',
            new_name='skill_name',
        ),
    ]
