# Generated by Django 2.2 on 2020-10-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20201018_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Complete Name'),
        ),
    ]
