# Generated by Django 2.2 on 2020-10-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short_name', models.CharField(max_length=20, verbose_name='Short Name')),
                ('canceled', models.BooleanField(default=False, verbose_name='Canceled')),
            ],
        ),
    ]
