# Generated by Django 2.2 on 2020-10-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Short Name'),
        ),
    ]
