# Generated by Django 2.2 on 2020-10-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20201016_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='skill',
            field=models.ManyToManyField(to='department.Skills'),
        ),
    ]
