# Generated by Django 2.2 on 2020-10-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
